### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/hassio-plum-ecomax#2]
After copying the files to the custom_components folder the hass wont restart, complaining that plum_ecomax component is not found (I added it to configuration.xaml). What should I do ? Is the problem with the required PyPlumIO plugin which I presume is installed automatically ? Or not ? Can anybody explain ?

**Comment by denpamusic** [comment]
Hi! Thanks for feedback. I'm just guessing here, but maybe you moved whole project folder to `config/custom_components`, instead of moving just `plum_ecomax` folder from here: https://github.com/denpamusic/hassio-plum-ecomax/tree/main/custom_components. Please check that `manifest.json` is located at following path `config/custom_components/plum_ecomax/manifest.json` in your hass installation.

**Comment by svenlange2** [comment]
No just moved the "plum_ecomax" folder. The manifest.json file seems fine there just like in the repo. I am pretty sure the Pyplumio library is not part of the python installation in hass but i am not able to install it. I am using Hass OS. I run homeassistant from official system image. It means i have no access to pip not python to configure it separately. Could the missing library be the problem or is installed automatically ?

**Comment by denpamusic** [comment]
That's strange. External dependencies listed in `manifest.json` are handled by hass automatically. It works fine in my standalone installation and, although untested, should be the same in hass OS. You error indicates that your hass installation can't find `manifest.json` in first place. Do you, by any chance, have any other components installed in `custom_components` folder? Just to check that hass can find components at all.

**Comment by denpamusic** [comment]
On an official Hass community it's recommended that before you add line to `configuration.yaml`, you should copy files to custom_components, restart hass, then add the line and restart hass again.

https://community.home-assistant.io/t/custom-components-on-home-assistant-operating-system/332411/4

**Comment by svenlange2** [comment]
It started to work! I had to disable the configuration.xaml entry and restart. Then presumably the dependency was fixed (during restart). After that when i enabled the "plum_ecomax" in configuration - is did not complain anymore and I was able to find the integration.

**Comment by denpamusic** [comment]
Great that it works now!

However, please be advised that this integration is still in early stages of development, only tested on [ecoMAX 350R](https://www.plum.pl/wp-content/uploads/2019/10/Karta-katalogowa_ecoMAX350R_v2_PL.pdf) and might not work well (or at all) with other models. I still waiting for the arrival of my ecoMAX860 for testing. If it works(or doesn't) for you, I'll really appreciate if you provide short report on following:
- Regulator model
- Connection method (TCP or serial)
- Is there any ecoSTER panel connected to your regulator?
- Any error messages reported by hass.

Thank you beforehand!

**Comment by svenlange2** [comment]
I have EcoMAX920 controller and i am waiting for the the RS485 Wifi dongle for permanent connection. No ecoSTER device connected. When I get the connection up Ill sure report. I basically bought the burner because I found that HASS integration is actually possible.

**Comment by denpamusic** [comment]
Thanks. Report will be awesome! PyPlumIO (and by extension this project) was created based on unpacked ecoNET 300 firmware, which should on protocol level work with any ecoMAX model. But setup procedure can fail, as this integration looks for specific fields and they may not be available on certain ecoMAX’es. I’ll probably relax this checks a bit or implement fallbacks in coming days, so be sure to check for updates before trying.

**Comment by denpamusic** [comment]
Great that you've been able to sort out RS485 connection.
As for you current issues:

1. This is not an error, but an information (log level `info`) that PyPlumIO encountered frame type, that it doesn't know how to deal with. In this case it's frame 0x89, that is not defined in ecoNET300 firmware. I think you can safely ignore it, as it probably intended for other devices and ecoNET 300 just ignores unknown frames. Please note that you shouldn't really be seeing this messages in the first place, since [hass documentation](https://www.home-assistant.io/integrations/logger/) indicates that unless otherwise specified, all log level below `warning` are ignored. Anyway I've [lowered log level for FrameTypeError](https://github.com/denpamusic/PyPlumIO/commit/f6f94b99ac86a59644ea08fcd1434844b229ece8) even further to `debug` since I believe it fits better there.

2. This is not intended behavior, PyPlumIO should try to reconnect forever with 20 seconds in between retries. At glance I didn't find anything wrong with reconnect logic, maybe HASS somehow affecting it... I'll try to recreate this problem later today. I'm also thinking of implementing incremental timeout, so that the more it tries, the longer time it waits in between tries. Although connection disappearance is sub-optimal and you should try to solve it.

**Comment by denpamusic** [comment]
Moved re-connect problem to separate issue: https://github.com/denpamusic/PyPlumIO/issues/1
