### ISSUE TITLE
HASS errors

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/hassio-plum-ecomax#4]
There is an error in the custom component. Namely on connection.py, on line

  self._connection.set_eth(ip=await async_get_source_ip(self._hass))

HASS wont finalise setup of the integration and complains that the function "async_get_source_ip()" lacks required argument "target_ip". From official repo i was able to find that indeeed it needs this second argument. A possible fix i implemented to my own files was:

from homeassistant.components.network.const import IPV4_BROADCAST_ADDR
...
self._connection.set_eth(ip=await async_get_source_ip(self._hass,IPV4_BROADCAST_ADDR))

After that I got everything working and was actually able to turn the device on from HASS.

**Comment by denpamusic** [comment]
Thanks for contribution! It's actually pretty interesting since I've never encountered this error myself, and built-in local_ip integration uses this function without target_ip [here](https://github.com/home-assistant/core/blob/master/homeassistant/components/local_ip/sensor.py#L35).

I'll implement your fix though, since it doesn't brake anything.
